config/routes.rb
Rails.application.routes.draw do
  resources :players
  resources :users
  resources :contacts
  resources :lists
  resources :lineitems
  resources :recruit_lists
  get "access/new"
  get "access/create"
  get "access/destroy"
  get "admin/index"
  get "recruiter/index"

  root "recruiter#index" # sends recruiters that go to 'root page' to recruiter/index
  get "recruiter", to: "recruiter#index"
  get "admin", to: "admin#index"
  get "login", to: "access#new" # #new before
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  post "/access/new", to: "access#create"
  #  post "/access", to: "access#new"
end

app/models/list.rb
class List < ApplicationRecord
  has_many :lineitems, dependent: :destroy

  def add_item(player_id)
    current_item = self.lineitems.find_by(player_id: player_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = self.lineitems.build(player_id: player_id)      
    end
    current_item
  end

  def total_ratings
    lineitems.to_a.sum{|item| item.item_total_rating}
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy if @list.id == session[:list_id]
    respond_to do |format|
      format.html { redirect_to recruiter_url, notice: 'Recruiting list was successfully deleted!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def list_params
      params.fetch(:list, {})
    end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<%= form_with(model: list, local: true) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% list.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lists/_list.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end  %>
<h3>Players currently on your watchlist:</h3>

<table>
  <% @list.lineitems.each do |item| %>
  <tr>
    <td><%= item.player.name %> - (<%= item.quantity %>)</td>
    <td class = "item_rating"> <%= item.player.rating %></td>
  </tr>
  <% end %>
  <tr class = "total_ratings">
    <td colspan = "2"> Sum of ratings = </td>
    <td class = "total_cell"><%= @list.total_ratings %></td>
  </tr>
</table>

<%= button_to 'Clear Recruiting List', @list, method: :delete, data:{confirm: 'are you sure?'} %>
<%= button_to 'Message players', new_contact_path, method: :get %>


<%# <%= link_to 'Edit', edit_list_path(@list) %>
<%# <%= link_to 'Back', lists_path %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lists</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= link_to 'Show', list %></td>
        <td><%= link_to 'Edit', edit_list_path(list) %></td>
        <td><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New List', new_list_path %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end  %>
<h3>Players currently on your watchlist:</h3>

<table>
  <% @list.lineitems.each do |item| %>
  <tr>
    <td><%= item.player.name %> - (<%= item.quantity %>)</td>
    <td class = "item_rating"> <%= item.player.rating %></td>
  </tr>
  <% end %>
  <tr class = "total_ratings">
    <td colspan = "2"> Sum of ratings = </td>
    <td class = "total_cell"><%= @list.total_ratings %></td>
  </tr>
</table>

<%= button_to 'Clear Recruiting List', @list, method: :delete, data:{confirm: 'are you sure?'} %>

<%# <%= link_to 'Edit', edit_list_path(@list) %>
<%# <%= link_to 'Back', lists_path %>