config/routes.rb
Rails.application.routes.draw do
  resources :players
  resources :users
  resources :contacts
  resources :lists
  resources :lineitems
  resources :recruit_lists
  get "access/new"
  get "access/create"
  get "access/destroy"
  get "admin/index"
  get "recruiter/index"

  root "recruiter#index" # sends recruiters that go to 'root page' to recruiter/index
  get "recruiter", to: "recruiter#index"
  get "admin", to: "admin#index"
  get "login", to: "access#new" # #new before
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  post "/access/new", to: "access#create"
  #  post "/access", to: "access#new"
end

app/models/recruit_list.rb
class RecruitList < ApplicationRecord
  has_many :lineitems, dependent: :destroy
end

app/controllers/recruit_lists_controller.rb
class RecruitListsController < ApplicationController
  before_action :set_recruit_list, only: [:show, :edit, :update, :destroy]

  # GET /recruit_lists
  # GET /recruit_lists.json
  def index
    @recruit_lists = RecruitList.all
  end

  # GET /recruit_lists/1
  # GET /recruit_lists/1.json
  def show
  end

  # GET /recruit_lists/new
  def new
    @recruit_list = RecruitList.new
  end

  # GET /recruit_lists/1/edit
  def edit
  end

  # POST /recruit_lists
  # POST /recruit_lists.json
  def create
    @recruit_list = RecruitList.new(recruit_list_params)

    respond_to do |format|
      if @recruit_list.save
        format.html { redirect_to @recruit_list, notice: 'Recruit list was successfully created.' }
        format.json { render :show, status: :created, location: @recruit_list }
      else
        format.html { render :new }
        format.json { render json: @recruit_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recruit_lists/1
  # PATCH/PUT /recruit_lists/1.json
  def update
    respond_to do |format|
      if @recruit_list.update(recruit_list_params)
        format.html { redirect_to @recruit_list, notice: 'Recruit list was successfully updated.' }
        format.json { render :show, status: :ok, location: @recruit_list }
      else
        format.html { render :edit }
        format.json { render json: @recruit_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recruit_lists/1
  # DELETE /recruit_lists/1.json
  def destroy
    @recruit_list.destroy
    respond_to do |format|
      format.html { redirect_to recruit_lists_url, notice: 'Recruit list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recruit_list
      @recruit_list = RecruitList.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def recruit_list_params
      params.fetch(:recruit_list, {})
    end
end

app/helpers/recruit_lists_helper.rb
module RecruitListsHelper
end

app/views/recruit_lists/_form.html.erb
<%= form_with(model: recruit_list, local: true) do |form| %>
  <% if recruit_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recruit_list.errors.count, "error") %> prohibited this recruit_list from being saved:</h2>

      <ul>
        <% recruit_list.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/recruit_lists/edit.html.erb
<h1>Editing Recruit List</h1>

<%= render 'form', recruit_list: @recruit_list %>

<%= link_to 'Show', @recruit_list %> |
<%= link_to 'Back', recruit_lists_path %>

app/views/recruit_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recruit Lists</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recruit_lists.each do |recruit_list| %>
      <tr>
        <td><%= link_to 'Show', recruit_list %></td>
        <td><%= link_to 'Edit', edit_recruit_list_path(recruit_list) %></td>
        <td><%= link_to 'Destroy', recruit_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recruit List', new_recruit_list_path %>

app/views/recruit_lists/new.html.erb
<h1>New Recruit List</h1>

<%= render 'form', recruit_list: @recruit_list %>

<%= link_to 'Back', recruit_lists_path %>

app/views/recruit_lists/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_recruit_list_path(@recruit_list) %> |
<%= link_to 'Back', recruit_lists_path %>