config/routes.rb
Rails.application.routes.draw do
  resources :players
  resources :users
  resources :contacts
  resources :lists
  resources :lineitems
  resources :recruit_lists
  get "access/new"
  get "access/create"
  get "access/destroy"
  get "admin/index"
  get "recruiter/index"

  root "recruiter#index" # sends recruiters that go to 'root page' to recruiter/index
  get "recruiter", to: "recruiter#index"
  get "admin", to: "admin#index"
  get "login", to: "access#new" # #new before
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  post "/access/new", to: "access#create"
  #  post "/access", to: "access#new"
end

app/models/player.rb
class Player < ApplicationRecord
  has_many :lineitems

  before_destroy :make_sure_no_line_items_in_any_cart
  validates(:name, :description, :image, presence: true) #make sure these are entered into each player
  validates :name, uniqueness: true #each name has to be unique
  validates :rating, numericality: {greater_than_or_equal_to: 1.00} #every rating must be greater than 1 bc rating scale is 1-5
  validates :image, allow_blank:true, format: {with: %r{\.(jpg|png)\Z}i, message: 'Image must be a JPG or PNG file type'}

  # instance method
  def make_sure_no_line_items_in_any_cart
    if self.lineitems.empty?
      return true
    else 
      errors.add(:base, "Line Items Present")
      retrun false
    end

  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  include CurrentList
  before_action :set_list
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.order(:rating)
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def player_params
      params.require(:player).permit(:name, :description, :image, :rating)
    end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= form_with(model: player, local: true) do |form| %>
  <% if player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>
      <ul>
        <% player.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, rows:10, cols:100 %>
  </div>
  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>
  <div class="field">
    <%= form.label :rating %>
    <%= form.text_field :rating %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end  %>
<h1>Draft Prospects</h1>
<table>
 
    <% @players.each do |player| %>
      <tr class = "<%=cycle('list_line_odd','list_line_even')%>">
        <td><%= image_tag(player.image, class: 'list_image') %></td>

        <td class="list_description">
        <dl>
        <h3 class = 'player_name'><dt><%= player.name %><br></dt></h3>
        <br>
        <dd><%= player.description %><br></dd>
        <dd class = "rating">Rating: <%= player.rating %>/5<br></dd></td>
      
        <td class ="list_actions">
        <button><%= link_to 'Show', player, :style=>'text-decoration: none; background-color: unset; color:unset;' %><br></button>
        <button><%= link_to 'Edit', edit_player_path(player), :style=>'text-decoration: none; background-color: unset; color:unset;' %><br></button>
        <button><%= link_to 'Destroy', player, :style=>'text-decoration: none; background-color: unset; color:unset;',method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
      </tr>
    <% end %>
<%# </tbody> %>
</table>
<br>
<p><%= link_to 'New Player', new_player_path %></p>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @player.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @player.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= @player.image %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @player.rating %>
</p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>